-- ============================================================================
-- 011_ref_tables_comprehensive_update.sql
-- Comprehensive update to ref lookup tables:
--   1. Add missing countries (MOLDOVA + worldwide coverage)
--   2. Add missing fruit aliases (singular/plural, typos)
--   3. Add missing country aliases
--   4. Add missing fruit entries (RENTAL excluded, VEGETABLE alias)
-- ============================================================================

-- ────────────────────────────────────────────────────────────────────────────
-- 1. ADD MISSING COUNTRIES — Comprehensive world coverage
-- ────────────────────────────────────────────────────────────────────────────

INSERT INTO ref_countries (name, abbreviation) VALUES
    -- Countries found in actual RDS data
    ('MOLDOVA',              'MD'),
    -- Major produce-exporting countries missing from original list
    ('COLOMBIA',             'CO'),
    ('COSTA RICA',           'CR'),
    ('CAMBODIA',             'KH'),
    ('DOMINICAN REPUBLIC',   'DO'),
    ('FIJI',                 'FJ'),
    ('GHANA',                'GH'),
    ('GUATEMALA',            'GT'),
    ('HONDURAS',             'HN'),
    ('IVORY COAST',          'CI'),
    ('LAOS',                 'LA'),
    ('MADAGASCAR',           'MG'),
    ('MYANMAR',              'MM'),
    ('NEPAL',                'NP'),
    ('NIGERIA',              'NG'),
    ('NORWAY',               'NO'),
    ('OMAN',                 'OM'),
    ('PANAMA',               'PA'),
    ('PARAGUAY',             'PY'),
    ('ROMANIA',              'RO'),
    ('RUSSIA',               'RU'),
    ('SINGAPORE',            'SG'),
    ('SRI LANKA',            'LK'),
    ('SWEDEN',               'SE'),
    ('SWITZERLAND',          'CH'),
    ('TANZANIA',             'TZ'),
    ('UGANDA',               'UG'),
    ('UNITED KINGDOM',       'GB'),
    ('URUGUAY',              'UY'),
    ('VENEZUELA',            'VE'),
    ('YEMEN',                'YE'),
    ('BANGLADESH',           'BD'),
    ('BULGARIA',             'BG'),
    ('CROATIA',              'HR'),
    ('CZECH REPUBLIC',       'CZ'),
    ('DENMARK',              'DK'),
    ('FINLAND',              'FI'),
    ('HUNGARY',              'HU'),
    ('IRELAND',              'IE'),
    ('JAMAICA',              'JM'),
    ('LIBYA',                'LY'),
    ('SENEGAL',              'SN'),
    ('SLOVAKIA',             'SK'),
    ('SLOVENIA',             'SI'),
    ('SOUTH KOREA',          'KR'),
    ('SURINAME',             'SR'),
    ('TONGA',                'TO'),
    ('TRINIDAD AND TOBAGO',  'TT'),
    ('PAPUA NEW GUINEA',     'PG'),
    ('CAMEROON',             'CM'),
    ('HAITI',                'HT'),
    ('CUBA',                 'CU'),
    ('IRAQ',                 'IQ'),
    ('KUWAIT',               'KW'),
    ('QATAR',                'QA'),
    ('BAHRAIN',              'BH'),
    ('AFGHANISTAN',          'AF'),
    ('SUDAN',                'SD'),
    ('ERITREA',              'ER'),
    ('SOMALIA',              'SO'),
    ('CHILE',                'CL'),
    ('CONGO',                'CD'),
    ('MALAWI',               'MW'),
    ('MOZAMBIQUE',           'MZ'),
    ('NAMIBIA',              'NA'),
    ('NIGER',                'NE'),
    ('BOTSWANA',             'BW'),
    ('BENIN',                'BJ'),
    ('BURKINA FASO',         'BF'),
    ('BURUNDI',              'BI'),
    ('CENTRAL AFRICAN REPUBLIC', 'CF'),
    ('CHAD',                 'TD'),
    ('COMOROS',              'KM'),
    ('DJIBOUTI',             'DJ'),
    ('EQUATORIAL GUINEA',    'GQ'),
    ('GABON',                'GA'),
    ('GAMBIA',               'GM'),
    ('GUINEA',               'GN'),
    ('GUINEA-BISSAU',        'GW'),
    ('LESOTHO',              'LS'),
    ('LIBERIA',              'LR'),
    ('MALI',                 'ML'),
    ('MAURITANIA',           'MR'),
    ('MAURITIUS',            'MU'),
    ('MONGOLIA',             'MN'),
    ('MONTENEGRO',           'ME'),
    ('NORTH MACEDONIA',      'MK'),
    ('SAMOA',                'WS'),
    ('SAO TOME AND PRINCIPE','ST'),
    ('SEYCHELLES',           'SC'),
    ('SIERRA LEONE',         'SL'),
    ('SOLOMON ISLANDS',      'SB'),
    ('ESWATINI',             'SZ'),
    ('TAJIKISTAN',           'TJ'),
    ('TIMOR-LESTE',          'TL'),
    ('TURKMENISTAN',         'TM'),
    ('TUVALU',               'TV'),
    ('VANUATU',              'VU'),
    ('KYRGYZSTAN',           'KG'),
    ('KAZAKHSTAN',           'KZ'),
    ('AZERBAIJAN',           'AZ'),
    ('ARMENIA',              'AM'),
    ('ALBANIA',              'AL'),
    ('ANDORRA',              'AD'),
    ('ANTIGUA AND BARBUDA',  'AG'),
    ('BARBADOS',             'BB'),
    ('BELIZE',               'BZ'),
    ('BHUTAN',               'BT'),
    ('BOLIVIA',              'BO'),
    ('BOSNIA AND HERZEGOVINA','BA'),
    ('BRUNEI DARUSSALAM',    'BN'),
    ('CAPE VERDE',           'CV'),
    ('DOMINICA',             'DM'),
    ('EL SALVADOR',          'SV'),
    ('GRENADA',              'GD'),
    ('GUYANA',               'GY'),
    ('ICELAND',              'IS'),
    ('KIRIBATI',             'KI'),
    ('KOSOVO',               'XK'),
    ('LATVIA',               'LV'),
    ('LIECHTENSTEIN',        'LI'),
    ('LITHUANIA',            'LT'),
    ('LUXEMBOURG',           'LU'),
    ('MALDIVES',             'MV'),
    ('MALTA',                'MT'),
    ('MARSHALL ISLANDS',     'MH'),
    ('MICRONESIA',           'FM'),
    ('MONACO',               'MC'),
    ('NAURU',                'NR'),
    ('NICARAGUA',            'NI'),
    ('NORTH KOREA',          'KP'),
    ('PALAU',                'PW'),
    ('SAINT KITTS AND NEVIS','KN'),
    ('SAINT LUCIA',          'LC'),
    ('SAN MARINO',           'SM'),
    ('TOGO',                 'TG'),
    ('EAST TIMOR',           'TL'),
    ('ESTONIA',              'EE'),
    ('AUSTRIA',              'AT')
ON CONFLICT DO NOTHING;

-- ────────────────────────────────────────────────────────────────────────────
-- 2. ADD MISSING FRUIT ALIASES — Singular/plural, typos, common variations
-- ────────────────────────────────────────────────────────────────────────────

INSERT INTO ref_fruit_aliases (alias, standard_name) VALUES
    -- Critical: singular forms missing from original migration
    ('DRAGON',        'DRAGON FRUITS'),
    ('VEGETABLE',     'VEGETABLES'),
    ('DRY FRUIT',     'DRY FRUITS'),
    -- Typos found in actual RDS UDF_BoC data
    ('POMEGRANTE',    'POMEGRANATE'),
    ('APRICORT',      'APRICOT'),
    -- Additional plural/singular variations
    ('AVOCADOS',      'AVOCADO'),
    ('BANANAS',       'BANANA'),
    ('CARROTS',       'CARROT'),
    ('CHESTNUTS',     'CHESTNUT'),
    ('COCONUTS',      'COCONUT'),
    ('DURIANS',       'DURIAN'),
    ('HONEYDEWS',     'HONEYDEW'),
    ('JACKFRUITS',    'JACKFRUIT'),
    ('KUMQUAT',       'KAMQUAT'),
    ('KUMQUATS',      'KAMQUAT'),
    ('LONGANS',       'LONGAN'),
    ('LYCHEES',       'LYCHEE'),
    ('LITCHI',        'LYCHEE'),
    ('LITCHIS',       'LYCHEE'),
    ('MANDARINS',     'MANDARIN'),
    ('MELONS',        'MELON'),
    ('NECTARINES',    'NECTARINE'),
    ('PAPAYAS',       'PAPAYA'),
    ('PINEAPPLES',    'PINEAPPLE'),
    ('PRUNE',         'PRUNES'),
    ('PUMPKINS',      'PUMPKIN'),
    ('RAMBUTANS',     'RAMBUTAN'),
    ('SWEET POTATOES','SWEET POTATO'),
    ('WATERMELON',    'MELON'),
    ('WATERMELONS',   'MELON'),
    ('TANGERINE',     'MANDARIN'),
    ('TANGERINES',    'MANDARIN'),
    ('CLEMENTINE',    'MANDARIN'),
    ('CLEMENTINES',   'MANDARIN'),
    ('SATSUMA',       'MANDARIN'),
    ('SATSUMAS',      'MANDARIN'),
    ('WOGAN',         'MANDARIN'),
    ('MIKAN',         'MANDARIN'),
    ('GINGER',        'VEGETABLES'),
    ('ONION',         'VEGETABLES'),
    ('ONIONS',        'VEGETABLES')
ON CONFLICT DO NOTHING;

-- ────────────────────────────────────────────────────────────────────────────
-- 3. ADD MISSING COUNTRY ALIASES
-- ────────────────────────────────────────────────────────────────────────────

INSERT INTO ref_country_aliases (alias, standard_name) VALUES
    -- Aliases from item code prefixes found in RDS data
    ('ML',        'MOLDOVA'),
    ('SD',        'SUDAN'),
    ('NO',        'NORWAY'),
    -- Common abbreviations & alternate names
    ('UK',        'UNITED KINGDOM'),
    ('BRITAIN',   'UNITED KINGDOM'),
    ('ENGLAND',   'UNITED KINGDOM'),
    ('SG',        'SINGAPORE'),
    ('ID',        'INDONESIA'),
    ('PH',        'PHILIPPINES'),
    ('BR',        'BRAZIL'),
    ('CL',        'CHILE'),
    ('CO',        'COLOMBIA'),
    ('MX',        'MEXICO'),
    ('PE',        'PERU'),
    ('AR',        'ARGENTINA'),
    ('DE',        'GERMANY'),
    ('FR',        'FRANCE'),
    ('IT',        'ITALY'),
    ('ES',        'SPAIN'),
    ('PT',        'PORTUGAL'),
    ('GR',        'GREECE'),
    ('TR',        'TURKEY'),
    ('EG',        'EGYPT'),
    ('IN',        'INDIA'),
    ('PK',        'PAKISTAN'),
    ('BD',        'BANGLADESH'),
    ('LK',        'SRI LANKA'),
    ('MM',        'MYANMAR'),
    ('KH',        'CAMBODIA'),
    ('LA',        'LAOS'),
    ('TW',        'TAIWAN'),
    ('RU',        'RUSSIA'),
    ('RO',        'ROMANIA'),
    ('PL',        'POLAND'),
    ('SAUDIARABIA', 'SAUDI ARABIA'),
    ('S.AFRICA',  'SOUTH AFRICA'),
    ('S AFRICA',  'SOUTH AFRICA'),
    ('STH AFRICA','SOUTH AFRICA'),
    ('SOUTH KOREA','KOREA'),
    ('S.KOREA',   'KOREA'),
    ('S KOREA',   'KOREA'),
    ('N.ZEALAND', 'NEW ZEALAND'),
    ('N ZEALAND', 'NEW ZEALAND'),
    ('NEWZEALAND','NEW ZEALAND'),
    ('U.S.A',     'UNITED STATES'),
    ('U.S.A.',    'UNITED STATES'),
    ('AMERICA',   'UNITED STATES'),
    ('IPOH',      'LOCAL'),
    ('TAMBUN',    'LOCAL'),
    ('CAMERON',   'LOCAL'),
    ('CAMERON HIGHLANDS', 'LOCAL')
ON CONFLICT DO NOTHING;
