'use client';

import { useState } from 'react';
import { Loader2 } from 'lucide-react';
import type { InsightStatus, SectionInsightData } from '@/hooks/ai-insight/useInsightAnalysis';
import type { SummaryInsight } from '@/lib/ai-insight/types';
import { InsightDetailDialog } from './InsightDetailDialog';

interface AiInsightPanelProps {
  status: InsightStatus;
  data: SectionInsightData | null;
  error: string | null;
}

function InsightCard({
  insight,
  sentiment,
  onClick,
}: {
  insight: SummaryInsight;
  sentiment: 'good' | 'bad';
  onClick: () => void;
}) {
  const isGood = sentiment === 'good';
  return (
    <button
      onClick={onClick}
      className={`flex items-start gap-2 text-left w-full rounded-lg border px-3 py-2 transition-colors cursor-pointer ${
        isGood
          ? 'border-green-200 hover:bg-green-50'
          : 'border-red-200 hover:bg-red-50'
      }`}
    >
      <span
        className={`mt-1.5 shrink-0 h-2.5 w-2.5 rounded-full ${
          isGood ? 'bg-green-500' : 'bg-red-500'
        }`}
      />
      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-2 min-w-0">
          <span
            className={`text-sm font-semibold truncate ${isGood ? 'text-green-800' : 'text-red-800'}`}
            title={insight.title}
          >
            {insight.title}
          </span>
          {insight.metric && (
            <span
              className={`shrink-0 inline-block text-[11px] font-medium px-1.5 py-0.5 rounded ${
                isGood
                  ? 'bg-green-100 text-green-700'
                  : 'bg-red-100 text-red-700'
              }`}
            >
              {insight.metric}
            </span>
          )}
        </div>
        {(insight.summary || insight.detail) && (
          <p
            className="text-xs text-foreground mt-0.5 line-clamp-1"
            title={insight.summary ?? undefined}
          >
            {insight.summary
              ? insight.summary
              : (() => {
                  // Fallback for insights without a dedicated summary field — strip markdown
                  // from detail and pick first sentence. Handles both old "**Header:**" and
                  // new "**Header** (scope):" patterns.
                  const cleaned = insight.detail
                    .replace(/\*\*[^*]+?\*\*\s*(?:\([^)]*\))?\s*:?/g, '') // new format: **Header** (scope):
                    .replace(/\*\*[^*]+:\*\*/g, '')                        // old format: **Header:**
                    .replace(/[#|`\n]/g, ' ')
                    .replace(/\s+/g, ' ')
                    .trim();
                  const match = cleaned.match(/^(.+?\.\s)/);
                  return match ? match[1].trim() : cleaned.slice(0, 120);
                })()}
          </p>
        )}
      </div>
    </button>
  );
}

export function AiInsightPanel({
  status,
  data,
  error,
}: AiInsightPanelProps) {
  const [selectedInsight, setSelectedInsight] = useState<{ insight: SummaryInsight; sentiment: 'good' | 'bad' } | null>(null);

  const hasResults = status === 'complete' && data;

  const goodInsights = hasResults ? (data.summary_json?.good ?? []).slice(0, 3) : [];
  const badInsights = hasResults ? (data.summary_json?.bad ?? []).slice(0, 3) : [];
  const analysisScope = hasResults
    ? data.date_range_start && data.date_range_end
      ? `${new Date(data.date_range_start).toLocaleDateString()} – ${new Date(data.date_range_end).toLocaleDateString()}`
      : data.fiscal_year && data.fiscal_range
        ? `${data.fiscal_year} - ${data.fiscal_range.toUpperCase()}`
        : 'Current State'
    : '';

  return (
    <div className="rounded-b-md border border-t-0 border-primary/10 bg-background">
      {/* Main content area */}
      <div className="px-4 py-3 min-h-[80px]">
        {/* State 1: Never generated */}
        {status === 'idle' && !data && (
          <div className="flex flex-col items-center justify-center py-4 text-foreground">
            <p className="text-sm font-medium">No insights generated yet.</p>
            <p className="text-sm">Generated by the admin AI Insight batch.</p>
          </div>
        )}

        {/* Loading stored data */}
        {status === 'loading' && (
          <div className="flex items-center justify-center py-4 text-foreground">
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            <span className="text-sm">Loading...</span>
          </div>
        )}

        {/* State 2: Results */}
        {hasResults && data.summary_json && (
          <div>
            <div className="mb-3 flex flex-col gap-1 text-sm font-medium text-foreground sm:flex-row sm:items-center sm:justify-between">
              <span>Analysis: {analysisScope}</span>
              <span>Last Updated: {new Date(data.generated_at).toLocaleString()}</span>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {/* POSITIVE column */}
              <div>
                <p className="text-xs font-semibold tracking-wide text-green-700 uppercase mb-2">Positive</p>
                {goodInsights.length > 0 ? (
                  <div className="space-y-2">
                    {goodInsights.map((item, i) => (
                      <InsightCard
                        key={`good-${i}`}
                        insight={item}
                        sentiment="good"
                        onClick={() => setSelectedInsight({ insight: item, sentiment: 'good' })}
                      />
                    ))}
                  </div>
                ) : (
                  <p className="text-xs text-foreground py-2">No positive highlights found.</p>
                )}
              </div>

              {/* NEGATIVE column */}
              <div>
                <p className="text-xs font-semibold tracking-wide text-red-700 uppercase mb-2">Negative</p>
                {badInsights.length > 0 ? (
                  <div className="space-y-2">
                    {badInsights.map((item, i) => (
                      <InsightCard
                        key={`bad-${i}`}
                        insight={item}
                        sentiment="bad"
                        onClick={() => setSelectedInsight({ insight: item, sentiment: 'bad' })}
                      />
                    ))}
                  </div>
                ) : (
                  <p className="text-xs text-foreground py-2">No concerns found.</p>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Error state */}
        {status === 'error' && (
          <div className="flex flex-col items-center justify-center py-4">
            <p className="text-sm text-red-700 font-medium">{error || 'Analysis failed'}</p>
          </div>
        )}
      </div>

      {/* Insight Detail Dialog */}
      {selectedInsight && (
        <InsightDetailDialog
          open={!!selectedInsight}
          onClose={() => setSelectedInsight(null)}
          title={selectedInsight.insight.title}
          detail={selectedInsight.insight.detail}
          sentiment={selectedInsight.sentiment}
        />
      )}
    </div>
  );
}
