- generic [active] [ref=e1]:
  - button "Open Next.js Dev Tools" [ref=e7] [cursor=pointer]:
    - img [ref=e8]
  - alert [ref=e11]
  - generic [ref=e12]:
    - complementary [ref=e13]:
      - generic [ref=e14]
      - navigation [ref=e20]
    - main [ref=e67]:
      - generic [ref=e69]
      - generic [ref=e77]
  - generic [ref=e847]: Not Yet Due